{pkgs}: {
  deps = [
    pkgs.libsoup
    pkgs.libsoup_3
    pkgs.libjxl
    pkgs.webkitgtk
    pkgs.webkitgtk_6_0
    pkgs.libjpeg8
    pkgs.gst_all_1.gst-plugins-ugly
    pkgs.icu74
    pkgs.harfbuzzFull
    pkgs.libglvnd
    pkgs.libjpeg_turbo
    pkgs.gst_all_1.gst-libav
    pkgs.gst_all_1.gst-plugins-bad
    pkgs.x264
    pkgs.libmanette
    pkgs.wayland
    pkgs.libwebp
    pkgs.zlib
    pkgs.libpng
    pkgs.libjpeg
    pkgs.libepoxy
    pkgs.libavif
    pkgs.hyphen
    pkgs.libtasn1
    pkgs.nghttp2
    pkgs.libpsl
    pkgs.libsecret
    pkgs.enchant
    pkgs.woff2
    pkgs.flite
    pkgs.gst_all_1.gst-plugins-good
    pkgs.gst_all_1.gst-plugins-base
    pkgs.libgpg-error
    pkgs.libgcrypt
    pkgs.libopus
    pkgs.libevent
    pkgs.lcms2
    pkgs.libxslt
    pkgs.sqlite
    pkgs.libxml2
    pkgs.systemd
    pkgs.icu
    pkgs.graphene
    pkgs.vulkan-loader
    pkgs.harfbuzz
    pkgs.gtk4
    pkgs.gst_all_1.gstreamer
    pkgs.libgccjit
    pkgs.gcc-unwrapped
    pkgs.libgcc
    pkgs.xorg.libXrender
    pkgs.gdk-pixbuf
    pkgs.gtk3
    pkgs.xorg.libXi
    pkgs.xorg.libXcursor
    pkgs.freetype
    pkgs.fontconfig
    pkgs.cairo
    pkgs.pango
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libxcb
    pkgs.xorg.libX11
    pkgs.expat
    pkgs.dbus
    pkgs.alsa-lib
    pkgs.mesa
    pkgs.libxkbcommon
    pkgs.libdrm
    pkgs.cups
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.glib
  ];
}
